BEGIN
    u_sal_cl.pkg_cleansing_star.sales;
    u_sal_cl.pkg_cleansing_star.customers;
    u_sal_cl.pkg_cleansing_star.stores;
    u_sal_cl.pkg_cleansing_star.employees;
    u_sal_cl.pkg_cleansing_star.pizzas;
    u_sal_cl.pkg_cleansing_star.promotions;
    u_sal_cl.pkg_cleansing_star.payment_methods;
    u_sal_cl.pkg_cleansing_star.geo_locations;
    u_sal_cl.pkg_cleansing_star.dates;
    u_sal_cl.pkg_cleansing_star.gen_periods;
END;