CREATE OR REPLACE PACKAGE u_dw_cl.pkg_cleansing_load_ref_dates
AS
    CURSOR cur IS SELECT * FROM u_sa_dates_data.sa_dates;
    
    TYPE type1 IS TABLE OF u_sa_dates_data.sa_dates.DATE_KEY%TYPE;
    key_arr type1;
    TYPE type2 IS TABLE OF u_sa_dates_data.sa_dates.DATE_FULL_NUMBER%TYPE;
    full_number_arr type2;
    TYPE type3 IS TABLE OF u_sa_dates_data.sa_dates.DATE_FULL_STRING%TYPE;
    full_string_arr type3;
    TYPE type4 IS TABLE OF u_sa_dates_data.sa_dates.DATE_WEEKDAY_FL%TYPE;
    weekday_fl_arr type4;
    TYPE type5 IS TABLE OF u_sa_dates_data.sa_dates.DATE_US_CIVIL_HOLIDAY_FL%TYPE;
    us_civil_holiday_fl_arr type5;
    TYPE type6 IS TABLE OF u_sa_dates_data.sa_dates.DATE_LAST_DAY_OF_WEEK_FL%TYPE;
    last_day_of_week_fl_arr type6;
    TYPE type7 IS TABLE OF u_sa_dates_data.sa_dates.DATE_LAST_DAY_OF_MONTH_FL%TYPE;
    last_day_of_month_fl_arr type7;
    TYPE type8 IS TABLE OF u_sa_dates_data.sa_dates.DATE_LAST_DAY_OF_QTR_FL%TYPE;
    last_day_of_qtr_fl_arr type8;
    TYPE type9 IS TABLE OF u_sa_dates_data.sa_dates.DATE_LAST_DAY_OF_YR_FL%TYPE;
    last_day_of_yr_fl_arr type9;
    TYPE type10 IS TABLE OF u_sa_dates_data.sa_dates.DATE_DAY_OF_WEEK_NAME%TYPE;
    day_of_week_name_arr type10;
    TYPE type11 IS TABLE OF u_sa_dates_data.sa_dates.DATE_DAY_OF_WEEK_ABBR%TYPE;
    day_of_week_abbr_arr type11;
    TYPE type12 IS TABLE OF u_sa_dates_data.sa_dates.DATE_MONTH_NAME%TYPE;
    month_name_arr type12;
    TYPE type13 IS TABLE OF u_sa_dates_data.sa_dates.DATE_MONTH_NAME_ABBR%TYPE;
    month_name_abbr_arr type13;
    TYPE type14 IS TABLE OF u_sa_dates_data.sa_dates.DATE_DAY_NUMBER_OF_WEEK%TYPE;
    day_number_of_week_arr type14;
    TYPE type15 IS TABLE OF u_sa_dates_data.sa_dates.DATE_DAY_NUMBER_OF_MONTH%TYPE;
    day_number_of_month_arr type15;
    TYPE type16 IS TABLE OF u_sa_dates_data.sa_dates.DATE_DAY_NUMBER_OF_QTR%TYPE;
    day_number_of_qtr_arr type16;
    TYPE type17 IS TABLE OF u_sa_dates_data.sa_dates.DATE_DAY_NUMBER_OF_YR%TYPE;
    day_number_of_yr_arr type17;
    TYPE type18 IS TABLE OF u_sa_dates_data.sa_dates.DATE_WEEK_NUMBER_OF_MONTH%TYPE;
    week_number_of_month_arr type18;
    TYPE type19 IS TABLE OF u_sa_dates_data.sa_dates.DATE_WEEK_NUMBER_OF_QTR%TYPE;
    week_number_of_qtr_arr type19;
    TYPE type20 IS TABLE OF u_sa_dates_data.sa_dates.DATE_WEEK_NUMBER_OF_YR%TYPE;
    week_number_of_yr_arr type20;
    TYPE type21 IS TABLE OF u_sa_dates_data.sa_dates.DATE_MONTH_NUMBER_OF_YR%TYPE;
    month_number_of_year_arr type21;
    TYPE type22 IS TABLE OF u_sa_dates_data.sa_dates.DATE_QTR_NUMBER_OF_YR%TYPE;
    qtr_number_of_year_arr type22;
    TYPE type23 IS TABLE OF u_sa_dates_data.sa_dates.DATE_YEAR_NUMBER%TYPE;
    year_number_arr type23;
    TYPE type24 IS TABLE OF u_sa_dates_data.sa_dates.DATE_WEEK_BEGIN_DT%TYPE;
    week_begin_dt_arr type24;
    TYPE type25 IS TABLE OF u_sa_dates_data.sa_dates.DATE_WEEK_END_DT%TYPE;
    week_end_dt_arr type25;
    TYPE type26 IS TABLE OF u_sa_dates_data.sa_dates.DATE_MONTH_BEGIN_DT%TYPE;
    month_begin_dt_arr type26;
    TYPE type27 IS TABLE OF u_sa_dates_data.sa_dates.DATE_MONTH_END_DT%TYPE;
    month_end_dt_arr type27;
    TYPE type28 IS TABLE OF u_sa_dates_data.sa_dates.DATE_QTR_BEGIN_DT%TYPE;
    qtr_begin_dt_arr type28;
    TYPE type29 IS TABLE OF u_sa_dates_data.sa_dates.DATE_QTR_END_DT%TYPE;
    qrt_end_dt_arr type29;
    TYPE type30 IS TABLE OF u_sa_dates_data.sa_dates.DATE_YR_BEGIN_DT%TYPE;
    yr_begin_dt_arr type30;
    TYPE type31 IS TABLE OF u_sa_dates_data.sa_dates.DATE_YR_END_DT%TYPE;
    yr_end_dt_arr type31;
    
    PROCEDURE load_dates;
END;
/