CREATE OR REPLACE PACKAGE u_dw_cl.pkg_cleansing_load_ref_dates
AS
    DATE_KEY NUMBER;
    DATE_FULL_NUMBER VARCHAR2(20);
    DATE_FULL_STRING VARCHAR2(50);
    DATE_WEEKDAY_FL NUMBER;
    DATE_US_CIVIL_HOLIDAY_FL NUMBER;
    DATE_LAST_DAY_OF_WEEK_FL NUMBER;
    DATE_LAST_DAY_OF_MONTH_FL NUMBER;
    DATE_LAST_DAY_OF_QTR_FL NUMBER;
    DATE_LAST_DAY_OF_YR_FL NUMBER;
    DATE_DAY_OF_WEEK_NAME VARCHAR2(20);
    DATE_DAY_OF_WEEK_ABBR VARCHAR2(20);
    DATE_MONTH_NAME VARCHAR2(20);
    DATE_MONTH_NAME_ABBR VARCHAR2(20);
    DATE_DAY_NUMBER_OF_WEEK NUMBER;
    DATE_DAY_NUMBER_OF_MONTH NUMBER;
    DATE_DAY_NUMBER_OF_QTR NUMBER;
    DATE_DAY_NUMBER_OF_YR NUMBER;
    DATE_WEEK_NUMBER_OF_MONTH NUMBER;
    DATE_WEEK_NUMBER_OF_QTR NUMBER;
    DATE_WEEK_NUMBER_OF_YR NUMBER;
    DATE_MONTH_NUMBER_OF_YR NUMBER;
    DATE_QTR_NUMBER_OF_YR NUMBER;
    DATE_YEAR_NUMBER NUMBER;
    DATE_WEEK_BEGIN_DT DATE;
    DATE_WEEK_END_DT DATE;
    DATE_MONTH_BEGIN_DT DATE;
    DATE_MONTH_END_DT DATE;
    DATE_QTR_BEGIN_DT DATE;
    DATE_QTR_END_DT DATE;
    DATE_YR_BEGIN_DT DATE;
    DATE_YR_END_DT DATE;
    
    PROCEDURE load_dates;
END;
/